# Source: samueljoli/cyberpunk.nvim dark palette
foreground=#ffffff
background=#120b10
cursor=#ff0055

color0=#000000
color1=#ff1745
color2=#00ff84
color3=#fffc58
color4=#76c1ff
color5=#ff0055
color6=#00ffc8
color7=#ffffff
color8=#2B3E5A
color9=#ff4081
color10=#00ff9c
color11=#fffc58
color12=#d57bff
color13=#c592ff
color14=#00ffe9
color15=#ffffff
