# Source: olivercederborg/poimandres.nvim colorscheme poimandres
foreground=#e4f0fb
background=#1b1e28
cursor=#e4f0fb

color0=#171922
color1=#D0679D
color2=#5DE4C7
color3=#FFFAC2
color4=#89DDFF
color5=#FCC5E9
color6=#89DDFF
color7=#FFFFFF
color8=#171922
color9=#D0679D
color10=#5DE4C7
color11=#FFFAC2
color12=#ADD7FF
color13=#FCC5E9
color14=#ADD7FF
color15=#FFFFFF
