# Source: hyperb1iss/silkcircuit-nvim colorscheme silkcircuit
foreground=#f8f8f2
background=#12101a
cursor=#f8f8f2

color0=#12101a
color1=#ff69ff
color2=#50fa7b
color3=#f1fa8c
color4=#e135ff
color5=#ff00ff
color6=#80ffea
color7=#f8f8f2
color8=#637777
color9=#ff6363
color10=#50fa7b
color11=#ffffa5
color12=#82b1ff
color13=#ff69ff
color14=#5fffff
color15=#ffffff
